### ISSUE TITLE
Implement bad cases for timer reconstruction during startup

### ISSUE THREAD

**Issue by 5ebastianMeier** [essential-projects/timing#6]
#### Describe your issue

There is currently only one bad case handled in a way that prevents the application from starting up (https://github.com/essential-projects/timing/pull/5). But the bad cases are not all implemented and fully handled the way they need to be - e.g. this also has implications on the process engine as we might need to make sure that the start up order leaves room for executing elapsed timers before further process execution.

@ppoetschke may have further cases in mind since he wanted this issue as a reminder for future fixes.

#### How can others reproduce the issue?

---

#### Possible solution

---

#### What's your setup

---

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
@5ebastianMeier 

https://github.com/essential-projects/timing/pull/5

Has this been solved with this PR?
